{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "798dd8f9",
   "metadata": {},
   "source": [
    "Напишите функцию normality_by, которая принимает на вход dataframe c тремя переменными. Первая переменная количественная, вторая и третья имеют две градации и разбивают наши наблюдения на группы. Функция должна проверять распределение на нормальность в каждой получившейся группе и возвращать dataframe с результатами применения теста ﻿ shapiro.test ﻿﻿(формат вывода смотри ниже).\n",
    "\n",
    "Рассмотрим пример работы функции. В данных mtcars есть две группирующие переменные am и vs, и обе переменные имеют две градации 0 и 1. В результате получаем 4 группы:\n",
    "\n",
    "am vs\n",
    "\n",
    "1 1\n",
    "\n",
    "1 0\n",
    "\n",
    "0 1\n",
    "\n",
    "0 0\n",
    "\n",
    "Теперь для переменной mpg в каждой из четырех групп можно проверить распределение на нормальность при помощи функции shapiro.test  и вывести получившийся p-value:\n",
    "\n",
    "> normality_by(mtcars[, c(\"mpg\", \"am\", \"vs\")])\n",
    "\n",
    "  am vs   p_value\n",
    "  \n",
    "1  0  0 0.5041144\n",
    "\n",
    "2  0  1 0.6181271\n",
    "\n",
    "3  1  0 0.5841903\n",
    "\n",
    "4  1  1 0.4168822\n",
    "\n",
    "> test_data <- read.csv(\"https://stepic.org/media/attachments/course/524/test_for_norm.csv\")\n",
    "\n",
    "> str(test_data)\n",
    "\n",
    "'data.frame':\t40 obs. of  3 variables:\n",
    "\n",
    " $ x: num  10.9 14 8.1 11 9.5 11 8.5 11.7 5.4 6.8 ...\n",
    " \n",
    " $ y: int  1 1 0 1 1 0 0 0 0 1 ...\n",
    " \n",
    " $ z: int  2 2 2 3 3 3 3 3 2 3 ...\n",
    " \n",
    "> normality_by(test_data)\n",
    "\n",
    "  y z    p_value\n",
    "  \n",
    "1 0 2 0.21976723\n",
    "\n",
    "2 0 3 0.62381802\n",
    "\n",
    "3 1 2 0.19603547\n",
    "\n",
    "4 1 3 0.04782269\n",
    "\n",
    "Итого: функция должна возвращать dataframe размером 4 на 3. \n",
    "\n",
    "Название столбцов: \n",
    "1 — имя первой группирующей переменной\n",
    "2 — имя второй группирующей переменной\n",
    "3 — p_value\n",
    "\n",
    "Подсказка: хороший пример того, когда при помощи функции group_by и summarise из пакета dplyr решается в три строчки! Кстати, обработка данных при помощи dplyr разбирается в курсе Основы программирования на R, прикладываю ссылку на урок."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "29bf65d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "library(dplyr)\n",
    "normality_by <- function(test){\n",
    "  nm <- names(test)\n",
    "  tabl <- test %>%\n",
    "    group_by(y, z) %>%\n",
    "    summarise(shapiro.test(x)$p)\n",
    "  names(tabl) <- c(nm[2],nm[3],\"p_value\")\n",
    "  return(tabl)\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "3.6.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
